services:
  - type: web
    name: nlp-engine
    env: docker
    plan: free
    dockerContext: nlp-engine
    dockerfilePath: nlp-engine/Dockerfile
    envVars:
      - key: PORT
        value: 5000

  - type: web
    name: backend
    env: docker
    plan: free
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: prgi-db
          property: connectionString
      - key: NLP_SERVICE_URL
        value: http://nlp-engine:5000/api/v1/semantic/verify

databases:
  - name: prgi-db
    plan: free
