class ProbabilityService {
    /**
     * Calculates the probability of a title being verified based on the similarity score
     * and presence of any compliance violations.
     * 
     * @param {number} maxSimilarityScore 0 to 100
     * @param {Array} violations List of rule violations generated by other services
     * @returns {number} Probability percentage 0 to 100
     */
    calculate(maxSimilarityScore, violations) {
        let probability = 100 - maxSimilarityScore;

        // Apply a heavy penalty if rule flags triggered
        if (violations && violations.length > 0) {
            probability -= (violations.length * 20); // Arbitrary penalty weight for static rules
        }

        // Bound probability to [0, 100]
        if (probability < 0) probability = 0;
        if (probability > 100) probability = 100;

        return Math.floor(probability);
    }
}

module.exports = new ProbabilityService();
